name: mieka
favicon: null
layout_spectrum: 0.05683137197047472
typography_spectrum: 0.7747694298159331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.02884448249824345
  lightness: 0.18233392713591456
  saturation: 0.3686352490913123
  rhythmicContrast: 0.30168610299006104
purpose: []
